server:
  port: 8081

spring:
  application:
    name: drdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.12.200:3306/pro_drdp
    username: root
    password: "011026"
  redis:
    host: 192.168.12.200
    port: 6379
    password: "011026"
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis-plus:
  type-aliases-package: com.example.drdp.entity # 别名扫描包

logging:
  level:
    com.example.drdp: debug